services:
  - type: web
    name: induslink-api
    runtime: node
    plan: free
    repo: https://github.com/SagnikDey1503/induslink.git
    rootDir: .
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: induslink
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: induslink-web
    runtime: node
    plan: free
    repo: https://github.com/SagnikDey1503/induslink.git
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
